### ISSUE TITLE
Dataset used for sf_modelFinal.mat

### ISSUE THREAD

**Issue by arnike** [jponttuset/mcg#13]
Hi,
I'm not sure if it's appropriate place to ask, but I wonder what dataset was used to train the model **sf_modelFinal.mat**?

Thanks in advance,
Nikita

**Comment by jponttuset** [comment]
Hi Nikita,

I'm pretty sure it was the BSDS500, but I could not find the source right now, so I am not 100% certain.
In any case, I took a pre-trained from the authors directly.

Best,

**Comment by arnike** [comment]
Thanks for your reply! Just to be sure, for the proposals and boxes you provide on [your project website](https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/mcg/#results), the structured forest was pre-trained on the respective datasets. Is that correct?

Kind regards,
Nikita

**Comment by jponttuset** [comment]
They are all using the same Structured Forest trained on BSDS500.

**Comment by arnike** [comment]
I see, thank you!
