### ISSUE TITLE
Saved MCG proposals for COCO

### ISSUE THREAD

**Issue by IssamLaradji** [jponttuset/mcg#15]
For the proposals generated for COCO, was MCG pretrained only on PASCAL and BSD? or was it pretrained on COCO?

Thanks!
--Issam

**Comment by jponttuset** [comment]
Hi Issam,

Only PASCAL, maybe BSD, cannot remember, definitely not COCO.

May I recommend our newer version of MCG?
It's called COB, have a look at:
http://www.vision.ee.ethz.ch/~cvlsegmentation/cob/

Best,
