### ISSUE TITLE
A function couldn't be founded.

### ISSUE THREAD

**Issue by chaomartin** [jponttuset/mcg#18]
Dear author:
       there's a trouble about the function 'loadvar()' in the 'im2mcg.m' line 52. The compiler always told me that 'can't find the 'loadvar' function'.  so, i believe there should be several reasons. First, i didn't load some libraries or add some folder paths. Second, the function is lost in my download.
      I hope you can give me some tips when your time is convenient.
                                                                                                                        Yours Sincerely.

**Comment by jponttuset** [comment]
You should run the "install.m" script for the path where loadvar is to be added.
Also, please consider using COB, much better and faster than MCG :)

**Comment by ahappycutedog** [comment]
> 
> 
> Dear author:
> there's a trouble about the function 'loadvar()' in the 'im2mcg.m' line 52. The compiler always told me that 'can't find the 'loadvar' function'. so, i believe there should be several reasons. First, i didn't load some libraries or add some folder paths. Second, the function is lost in my download.
> I hope you can give me some tips when your time is convenient.
> Yours Sincerely.
Hi,  i want to know  how to deal with the problem?  i have run the install.m, but i alos not got the function.
