### ISSUE TITLE
Reference to non-existent field 'opts'

### ISSUE THREAD

**Issue by zsz1997** [jponttuset/mcg#20]
Hello, thank you for your code and it's really helpful for me. But when I run the code of demo_im2ucm/demo_im2mcg in full folder, it gets one error is 'Reference to non-existent field 'opts'', I found that it happens in edgesDetect.m, I can not understand why, so I'm looking forward to your answer. thanks~

**Comment by jponttuset** [comment]
The "full" package is not up to date (see README), I would suggest you use "pre-trained" as "full" is only needed to retrain the Pareto front, which you probably don't need.
