### ISSUE TITLE
Where is "Result" folders?

### ISSUE THREAD

**Issue by TongkunGuan** [jponttuset/mcg#27]
Dear author:
I can't find the 'results' folder in  https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/mcg/#results.
Precomputed results not found: Have you downloaded them? Visit the MCG website and download the 'results' folder.

**Comment by jponttuset** [comment]
Hi, you can find the pre-computed results under the "Datasets" section: https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/mcg/#datasets
