### ISSUE TITLE
mcg/pre-trained/src/aux should be renamed

### ISSUE THREAD

**Issue by ChanChiChoi** [jponttuset/mcg#8]
in windows system, the "aux" is a special directory name，so we should not use this to be directory name when want to compile the cpp code into matlab

**Comment by jponttuset** [comment]
As stated in the README:
"'Full' and 'Pre-Trained' packages not compatible with Windows."
For reasons beyond this folder, so even if we solved this, you would not be able to compile it.
Sorry about that. Maybe you should consider:
"Convolutional Oriented Boundaries", ECCV 2016: http://www.vision.ee.ethz.ch/~cvlsegmentation/cob/

**Comment by ChanChiChoi** [comment]
en,i see.thank you for your work and code
