### ISSUE TITLE
Use this code to group proposals

### ISSUE THREAD

**Issue by mangdian** [jponttuset/mcg#9]
How can I use this code to group my own generated proposals? Which script should I use?

**Comment by jponttuset** [comment]
Could you please be more specific in your question?

**Comment by mangdian** [comment]
@jponttuset Thank you for your responce. sorry, I don't express clearly. I am doing research about action detection in videos, which is similar to object detection.
In action detection task, the proposal list is in the following form:
12    36  0.58
38   128 0.99
210 880 0.85

the first two integer is the starting frame and end frame respectively and the third number is confidence score. How can I input such a proposal list to MCG and group those proposals?

**Comment by mangdian** [comment]
?

**Comment by jponttuset** [comment]
I don't see how MCG can help in this case, sorry.
